name: "Release prebuilt language server"

on: ["workflow_dispatch"]

jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    steps:
      - name: "Store timestamp"
        run: |
          echo "TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)" >> "$GITHUB_ENV"
      - uses: "actions/checkout@v4"
      - run: npm ci
      - run: npx lix run vshaxe-build -t language-server
      - uses: "ncipollo/release-action@v1"
        with:
          artifacts: "bin/server.js"
          body: "This artifact was built on $TIMESTAMP."
          commit: "${{ github.sha }}"
          makeLatest: "legacy"
          tag: |
            $TIMESTAMP
