name: "Release prebuilt language server"

on: ["workflow_dispatch"]

jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    steps:
      - name: "Store current timestamp"
        id: timestamp
        run: echo "DATE=$(date +%Y-%m-%d_%H-%M-%S)" >> "$GITHUB_OUTPUT"
      - uses: "actions/checkout@v4"
      - run: npm ci
      - run: npx lix run vshaxe-build -t language-server
      - uses: "ncipollo/release-action@v1"
        with:
          artifacts: "bin/server.js"
          body: "This artifact was built on ${{ steps.timestamp.outputs.DATE }}."
          commit: "${{ github.sha }}"
          makeLatest: "legacy"
          tag: "v${{ steps.timestamp.outputs.DATE }}"
